spring.application.name=FUExam

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fu_exam;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
springdoc.swagger-ui.path=/api-docs

server.servlet.context-path=/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=dd/MM/yyyy HH:mm:ss

jwt.secret=9a4f2c8d3b7a1e6f5c8d0e2b4a6c8e1f9a4f2c8d3b7a1e6f5c8d0e2b4a6c8e1f
jwt.expiration=86400000